### PR TITLE
Update SignInView.swift

### PR DESCRIPTION
**Pull request by Evilsmaher**
- Added `ProgressView` capabilities so the view isn't sitting idle without displaying something to the user

### CODE REVIEW

**Comment by john-royal** [comment]
Great idea! Just a few suggestions:
* Remove the `authenticating` state variable and use the `isInProgress` property of the `TaskViewModel` instead.
* The `.progressViewStyle(.circular)` modifier isn’t needed, since the circular style is used by default.
* I’m not sure if the `withAnimation(.none)` block is necessary.
* Consider displaying the `ProgressView` using an `if` statement, rather than using an `if`/`else` to render the same `content` twice.
* Consider using an `overlay` instead of a `ZStack`—just an idea.
* Regarding the computed `content` property: I don’t have a problem with it, but I think this project [favors structs over computed properties for subviews](https://github.com/benstone1/InstaCademy/pull/24#discussion_r701183998) (please correct me if I’m wrong).

**Comment by Evilsmaher** [comment]
@john-royal with your comments, plus a little research, I think I found a quick solution to create conditional modifiers without having to create a ternary operator or a set of structures that were going to create a pile of unnecessary code. Let me know your thoughts!

**Comment by john-royal** [comment]
LGTM! I love the `if` modifier—great work with that. My only feedback would be to consider moving the modifier to a separate file, since it's shared between the `SignInView` and `SignUpView`.

**Comment by Evilsmaher** [comment]
@john-royal Feel free to take charge on this - just trying to help where I can!

**Comment by Evilsmaher** [comment]
@benstone1 had asked me why we didn't just use a `ZStack` haha! To be honest, I just took @john-royal's advice and ran with it. Feel free to comment if you all were not already having a discussion behind the scenes.

**Comment by benstone1** [comment]
Closing this for now, as I think the `if` ViewBuilder adds a bit too much complexity.  Super interesting though.

**Pull request closed without merging**
